---
title: "housing prices"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(zoo)
library(dplyr)
library(MASS)
```

```{r}
resale <- read.csv("resale-flat-prices/resale-flat-prices-based-on-registration-date-from-march-2012-onwards.csv")
sublet <- read.csv("resale-flat-prices/subletting-approvals-by-flat-type-quarterly.csv")
sublet.rent <- read.csv("resale-flat-prices/median-subletting-rental-by-town-and-flat-type.csv", na.strings = c("na", "-"))
```

```{r}
head(resale)
summary(resale)
```

convert flat type to same format
```{r}
unique(resale$flat_type)
unique(sublet$flat_type)
sublet$flat_type <- toupper(gsub("-", " ", sublet$flat_type))

unique(sublet.rent$flat_type)
sublet.rent$flat_type <- gsub("EXEC", "EXECUTIVE", gsub("-RM", " ROOM",sublet.rent$flat_type))
# sublet.rent$median_subletting_rents <- as.numeric(sublet.rent$median_subletting_rents)

```

add quarter column to resale
```{r}
resale$quarter <- format(as.yearqtr(as.yearmon(resale$month)), "%Y-Q%q")
sublet$sublet_per_month <- sublet$no_of_approvals / 3

resale.sublet <- merge(resale, sublet[,c("quarter","flat_type", "sublet_per_month")], by = c("quarter", "flat_type"), all.x = TRUE)
resale.sublet <- merge(resale.sublet, sublet.rent, by = c("quarter","flat_type","town"), all.x = TRUE)

```

get median price
```{r}
resale.sublet.median <- resale.sublet %>%
  group_by(month, flat_type) %>%
  summarize(median_price = median(resale_price),
            sublet_per_month = mean(sublet_per_month))
resale.sublet.median
```

```{r}
p.sublet.price <- ggplot(resale.sublet.median[!is.na(resale.sublet.median$sublet_per_month),], aes(x = sublet_per_month, y=median_price,color=flat_type)) + geom_point(alpha = 0.5) + geom_smooth()
p.sublet.price

```

```{r}
ggplot(resale.sublet.median, aes(x = month, y=median_price,color=sublet_per_month)) + geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_wrap(~.flat_type)

```


```{r}
resale.sublet.rent <- resale.sublet %>%
  group_by(month, flat_type, town) %>%
  summarize(median_price = median(resale_price),
            sublet_per_month = mean(sublet_per_month),
            sublet_rent = mean(median_subletting_rents, na.rm=TRUE))
resale.sublet.rent
```

```{r}
p.rent.price <- ggplot(resale.sublet.rent, aes(x = sublet_rent, y=median_price,color=town)) + geom_point(alpha = 0.5) +  facet_wrap(~flat_type)
# geom_smooth() +
p.rent.price

```
for 5 room flats, for towns with flats price < $600,000, price is correlated with sublet rent. towns with flats above that price, sublet rent is weakly correlated with sublet rent.
```{r}
five_room <- resale.sublet.rent[resale.sublet.rent$flat_type == "5 ROOM",]
ggplot(five_room, aes(x = sublet_rent, y=median_price,color=town)) + geom_point(alpha = 0.5) + geom_smooth(method="lm")

```

```{r}
four_room <- resale.sublet.rent[resale.sublet.rent$flat_type == "4 ROOM",]
ggplot(four_room, aes(x = sublet_rent, y=median_price,color=town)) + geom_point(alpha = 0.5) + geom_smooth(method="lm")

```
sublet price vs number
```{r}
p.rent.number <- ggplot(resale.sublet.rent, aes(x = sublet_rent, y=sublet_per_month,color=town)) + geom_point(alpha = 0.5) +  facet_wrap(~flat_type)
# geom_smooth() +
p.rent.number

```
```{r}
ggplot(resale.sublet.rent[resale.sublet.rent$flat_type == "5 ROOM",], aes(x = sublet_rent, y=sublet_per_month,color=town)) + geom_point(alpha = 0.5) + geom_smooth()
```

```{r}
ggplot(resale.sublet[resale.sublet$flat_type == "5 ROOM",], aes(x=median_subletting_rents,y=resale_price)) + geom_point(alpha = 0.5) + facet_wrap(~town)

```

```{r}
resale.sublet$year <- substr(resale.sublet$quarter, 1,4)
```

```{r}
recent.years <- resale.sublet[resale.sublet$year >= 2015,]
recent.years$year <- factor(recent.years$year)
summary(resale.sublet)
# m1 <- lm(resale_price ~ . -quarter - month - sublet_per_month - floor_area_sqm, data = resale.sublet)
m1 <- lm(resale_price ~ flat_type + town + storey_range + flat_model + lease_commence_date + sublet_per_month, data = recent.years)
summary(m1)
```

```{r}
m1$coefficients[2:6]
m1$xlevels[1]

coeff <- data.frame(m1$coefficients)
coeff$category <- as.character(rownames(coeff))
colnames(coeff) <- c("change in price", "category")

rooms <- coeff[2:6,]
rooms <- rbind(rooms, c(0, "flat_type1 ROOM"))
ggplot(rooms, aes(x=`change in price`, y=category))+ geom_point()


```

```{r}
m1$coefficients

m1$coefficients[7:31]
m1$xlevels[2]
coeff

coeff <- data.frame(m1$coefficients)
coeff$category <- as.character(rownames(coeff))
colnames(coeff) <- c("change in price", "category")

rooms <- coeff[7:31,]
rooms <- rbind(rooms, c(0, "ANG MO KIO"))
ggplot(rooms, aes(x=`change in price`, y=category))+ geom_point()

```
```{r}
towns <- coeff[7:31,]
towns <- rbind(towns, c(0, "ANG MO KIO"))
ggplot(towns, aes(x=`change in price`, y=category)) + geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
storey <- coeff[32:47,]
storey
storey <- rbind(storey, c(0, "storey 0 to 3"))
ggplot(storey, aes(x=`change in price`, y=category)) + geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ks.test(m1$residuals, pnorm, mean(m1$residuals), sd(m1$residuals))
```

```{r}
m2 <- lm(resale_price ~ flat_type + town + storey_range + lease_commence_date + sublet_per_month, data = resale.sublet)
summary(m2)
plot(m2)
```


```{r}
ks.test(m2$residuals, pnorm, mean(m2$residuals), sd(m2$residuals))
```

```{r}
stepAIC(m1, direction = "backward")
```
```{r}

m3 <- lm(resale_price ~ floor_area_sqm + town + storey_range + lease_commence_date + sublet_per_month, data = resale.sublet)
summary(m3)
plot(m3)
ks.test(m3$residuals, pnorm, mean(m3$residuals), sd(m3$residuals))
```

```{r}
m0 <- lm(resale_price ~ 1, resale.sublet)

```

```{r}

stepAIC(m1, direction = "both")
```

